### ISSUE TITLE
etl_load() error

### ISSUE THREAD

**Issue by kjryan13** [beanumber/statcastr#1]
I am running R v3.5.2 with mysql server version 8.0.15 Homebrew on Mac OS 10.14.3. The following chunk of code produces the given error in the call to etl_load. A fix would be greatly appreciated.

library(statcastr)
library(RMySQL)
db <- src_mysql_cnf("statcast")
sc <- etl("statcastr", db, dir = "~/dumps/statcastr")
sc %>%
 etl_extract(year = 2017, month = 3:10) %>%
   etl_transform() %>%
     etl_load(tablenames = "statcast")

Error in .local(conn, statement, ...) : 
  could not run statement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-2017-8-all 
( `pitch_type` text,
	`game_date` text,
	`release_speed` double,
	`' at line 1

**Comment by beanumber** [comment]
Confirmed. There is a bug in `etl::smart_upload()`. 

Thanks!

**Comment by beanumber** [comment]
This should be working now. @kjryan13 you have a couple of options:

1. You can re-install `statcastr` and run your code again. This will cause the data files to be downloaded again. 
2. You can rename the files you already downloaded by replacing dashes with underscores. Then run `etl::load(sc, tablenames = "statcast")`
