### ISSUE TITLE
When I try to install 'statcastr' I get an error.

### ISSUE THREAD

**Issue by EveryFreyday** [beanumber/statcastr#5]
ERROR: lazy loading failed for package ‘statcastr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/statcastr’
Error: Failed to install 'statcastr' from GitHub:
  (converted from warning) installation of package ‘/var/folders/2d/sdpmgxzs0qvb95xyrq3njx5r0000gp/T//RtmpIbeHzV/filef9c06c021585/statcastr_0.0.0.9003.tar.gz’ had non-zero exit status

It is my understanding that this comes from an issue inside the package.

**Comment by beanumber** [comment]
@EveryFreyday if you scroll up, is there another message about a package installation that failed? My guess is that one of the dependencies failed to install, and that's why `statcastr` failed to install.

**Comment by EveryFreyday** [comment]
Here is the full message. R will not let me install it from the GUI so I used the devtools installation.

<img width="784" alt="Screen Shot 2020-12-08 at 11 38 24 AM" src="https://user-images.githubusercontent.com/17477040/101513335-0f2e7c80-394a-11eb-9375-5a50b1ad9393.png">
`

**Comment by beanumber** [comment]
Can you try: `install.packages("etl")` and then try again?

**Comment by EveryFreyday** [comment]
Installing "etl" worked, but "statcastr" failed to install again.

<img width="787" alt="Screen Shot 2020-12-08 at 12 05 52 PM" src="https://user-images.githubusercontent.com/17477040/101516696-c973b300-394d-11eb-9f1c-71e31f311eea.png">

**Comment by beanumber** [comment]
Hmm...I'm not sure what the problem is. 

I don't suppose you would want to upgrade to R 4.0?

**Comment by EveryFreyday** [comment]
I updated my R and R Studio. I now get this error. Sorry to be a bother.

<img width="788" alt="Screen Shot 2020-12-08 at 3 38 38 PM" src="https://user-images.githubusercontent.com/17477040/101538709-845e7980-396b-11eb-9b23-83709c2a50eb.png">

**Comment by EveryFreyday** [comment]
Fixed it. I installed data.table, which I do not think was necessary. Then I encountered the error message `Do you want to install from sources the package which needs compilation?` When I answered yes to this, the package would not install. When I answered no to it, the installation was successful. 

Thank you for the help.

**Comment by beanumber** [comment]
@EveryFreyday OK, nice! Sorry this was such a pain.
